### ISSUE TITLE
Exception when trying to command Grohe Sense Guard

### ISSUE THREAD

**Issue by petitpiton** [windkh/node-red-contrib-grohe-sense#1]
Using this node in Home Assistant, the note returns the correct status information when I inject a timestamp.  However, when I try to send a command to open or close the valve an exception is generated as follows:

Caught exception:
TypeError: Promise resolver undefined is not a function
when processing message: 
{"_msgid":"d88c4bd403322916","payload":{"command":{"valve_open":false},"type":103},"topic":""}

**Comment by windkh** [comment]
what version do you have?

**Comment by windkh** [comment]
Maybe you send me your flow so that I can crosscheck

**Comment by petitpiton** [comment]
> what version do you have?

I have version 0.5.4

**Comment by petitpiton** [comment]
> Maybe you send me your flow so that I can crosscheck
[flows.txt](https://github.com/windkh/node-red-contrib-grohe-sense/files/8087639/flows.txt)

**Comment by windkh** [comment]
I found something... thanks for reporting. Will release a new version asap.

**Comment by windkh** [comment]
0.6.0 should fix this. Sorry but with the last commit some changes were not pushed before making the release

**Comment by petitpiton** [comment]
> 0.6.0 should fix this. Sorry but with the last commit some changes were not pushed before making the release

I can confirm it's working for me with 0.6.0. Thank you.
