### ISSUE TITLE
How can I get actual data of measurements and withdrawals?

### ISSUE THREAD

**Issue by pschyrembel258** [windkh/node-red-contrib-grohe-sense#10]
I've used the function node for historical data of the example and set it to -1. But the output is only from the day before today. How can I get actual values of the last measurement and withdrawal.

**Comment by windkh** [comment]
The sense device sends historical data from time to time into the cloud. The data you get from the node is the data already stored in the cloud. Grohe does not allow to talk to the sense device directly from within the local lan. Every communication is done via a cloud server. Sorry ...

**Comment by windkh** [comment]
I think that the sense devices send the latest values every hour into the cloud. So you can not have "live" values but at least "not so old ones"

**Comment by windkh** [comment]
@pschyrembel258 please try out 0.13.0
