### ISSUE TITLE
Caught exception: Cannot read properties of undefined

### ISSUE THREAD

**Issue by 4Fire4** [windkh/node-red-contrib-grohe-sense#11]
I'm new to Node-RED and HA, so I just tried to import the examples to try this.

I managed to set the location, user, pw, room, name and type. When I deploy, the Guard has a green square and "connected" status. But if I  start "timestamp" (or anything else), I get "failed" and this error in the debug: "Caught exception: Cannot read properties of undefined (reading 'type')"

Any hint at what I'm doing wrong?

![image](https://user-images.githubusercontent.com/26690347/222990883-096b7121-cab1-47a4-b70a-1f2e60fabf6f.png)

**Comment by windkh** [comment]
@4Fire4 I never saw this before. To know what is going on I would need to debug the node or I would need more information. 
On what platform do you run node-red? 
Maybe we can arrange a teams meeting?

**Comment by 4Fire4** [comment]
I'm running "Home Assistant Operating System" on a Raspberry Pi 4.
Yes, we can arrange a teams meeting.

**Comment by windkh** [comment]
Reason: conversion of notification response fails as category 40 is not known: make the conversion more robust

**Comment by windkh** [comment]
please install new version 0.15.1 and let me know if it works for you

**Comment by 4Fire4** [comment]
Tested with both Windows and Home Assistand on Raspberry Pi 4 and it works :) 

I had two unread of those category 40 notifications, which seem to be not normal notifications. More like a "Did you have a leak?" questionnaire that I got due to previously detected potential leak notifications.

Thanks @windkh!

**Comment by 4Fire4** [comment]
I had a look at "ondusApi.js" and you say category 40 is "unkown, maybe info". Here is a screenshot of that specific notification category 40, which seems to be a questionnaire or request for feedback:

![Screenshot_20230318_135025](https://user-images.githubusercontent.com/26690347/226108177-a1d7607d-dcdb-49e6-a462-7bb757dc9265.jpg)

**Comment by windkh** [comment]
@4Fire4  thanks for testing... yes indeed I also thought maybe the category is "question" but as this is the only type in category 40 I saw so far I left this open for now. Maybe more types in this category will be reported in future, then we will know for sure what 40 really means.

**Comment by windkh** [comment]
@4Fire4  I found out that category 0 is reserved for advertising and category 40 seems to be an external web url
