### ISSUE TITLE
Problem with get data from GroheSense 

### ISSUE THREAD

**Issue by Andware** [windkh/node-red-contrib-grohe-sense#12]
Problem with get data from GroheSense since HomeAssistant version 2023.9 NodeRed

I don't know if GroheSense has changed something in their API or if it's in HA

Anyone else having issues with the GroheSens integration?

![Skærmbillede 2023-09-12 kl  15 11 08](https://github.com/windkh/node-red-contrib-grohe-sense/assets/3460191/1cbaf064-f722-4f4a-8fb5-cbc429a82e03)

**Comment by MaximilianSchultz** [comment]
Hi together,
have the same problem.
getting only information of the device itselfe, but nothing regarding the water Flow, Pressure, Temp, ...

were there an update or anything lile that?
Many thanks in advance.

**Comment by tbkflatekvaal** [comment]
Both "data" and "statistics" are gone from the response from Grohe.
I guess some new API calls needs to be done to get these data now?

**Comment by windkh** [comment]
Hm maybe the API changed... if that would be the case it is not good news.

**Comment by windkh** [comment]
@Floppe thanks, that worked.. how did you find out?

**Comment by windkh** [comment]
version 0.16.0 should fix this

**Comment by Floppe** [comment]
@windkh I used mitmproxy on their Android app. Thanks for a quick fix, will try it out.

**Comment by windkh** [comment]
Ah I see thanks alot
