### ISSUE TITLE
How to get newest values?

### ISSUE THREAD

**Issue by PottiMc** [windkh/node-red-contrib-grohe-sense#13]
At first, thank you very much for fixing this and adjusting the Node Red Version to the new API style very fast!

I have one question:
How is it possible to see the newest values of my Sense Guard? As far as I see the standard response is grouped by days and it's just the daily average:

![grafik](https://github.com/windkh/node-red-contrib-grohe-sense/assets/39881308/c57455ce-31d7-4113-95fc-9b018cdc5be6)

Is it possible to change this to "hour" at least? I was not able to get an hour response with your example blocks.

**Comment by windkh** [comment]
I guess that after the api changed some details are missing in withdrawals: start and stop time maxflowrate, timestampmis rounded to day and so on.

**Comment by PottiMc** [comment]
> Well, the data is transfered from the device to the cloud from time to time. From there the node retrieves the data. I can try to change this to hours...
> The data under withdrawals is the most accurate you can get.

Sorry, I was unclear. Withdrawals are fine, these are accurate in the 15 minute timeframe the Ondus API is allowing. I was talking about pressure and water temperature. The values in the app are still accurate and on an hourly basis. 
I thought there is an easy way to switch to an hourly base when requesting the data because in Issue #12 a user is having an hour request.

**Comment by windkh** [comment]
You are right, I did not see this at first. 

groupBy=hour&from=2023-08-18&to=2023-09-17

I will add this at the weekend. Thanks for pointing out

**Comment by windkh** [comment]
0.17.0 should work for you.

**Comment by PottiMc** [comment]
@windkh 
I can't test it the next 2 or 3 weeks but I already thank you for your work!
