### ISSUE TITLE
same values in total and todays water consumption

### ISSUE THREAD

**Issue by pschyrembel258** [windkh/node-red-contrib-grohe-sense#14]
Hello,

I have equal values for todays water consumption and total water consumption under the statistical section of the payload. The other statistical values are also the same, but I don't use them

Since the api change my todays water consumption was 0, after updating your node I got this behavior.
<img width="272" alt="Bildschirmfoto 2023-09-25 um 14 48 54" src="https://github.com/windkh/node-red-contrib-grohe-sense/assets/25116704/8dc15eb6-0238-458b-886b-5726ac41feee">

Thanks 

Daniel

**Comment by windkh** [comment]
@pschyrembel258 ah ok I got it:
if you only request data from one day then total and today is the same. It would be different if you would check the data for one week, then total would be the sum of the whole week while today would be the consumption of only the last day

**Comment by pschyrembel258** [comment]
But I've only had 190 liters consumed today and not more than 400. something is not working properly for me.

**Comment by windkh** [comment]
Ok I will check it with my data...

**Comment by windkh** [comment]
I found the reason: the data returned is now sorted in descending order and not in ascending. I will fix it now.

**Comment by windkh** [comment]
0.18.0 should contain the fix, thanks for reporting
