### ISSUE TITLE
Stuck initializing status

### ISSUE THREAD

**Issue by rirac** [windkh/node-red-contrib-grohe-sense#15]
Hello,

I am stuck on "initializing" status with no debug information in console.

![image](https://github.com/windkh/node-red-contrib-grohe-sense/assets/95582028/ac9e0dc2-8303-4dcd-964d-bbd25765b853)

I am sure that my login information are correct.

Do you have any idea what could be wrong? Or any tips how can I debug the flow will be appreciated.

Thanks!

**Comment by windkh** [comment]
Did it work before?

**Comment by rirac** [comment]
Nope, trying to set it up first time.

**Comment by windkh** [comment]
Can you show the configuration?

**Comment by rirac** [comment]
Here it is. I just imported there your examples:

`[
    {
        "id": "28a8416547d8a5d5",
        "type": "tab",
        "label": "Flow 2",
        "disabled": true,
        "info": "",
        "env": []
    },
    {
        "id": "d4e111d3e6674702",
        "type": "inject",
        "z": "28a8416547d8a5d5",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 260,
        "y": 540,
        "wires": [
            [
                "ed7589d527fde314"
            ]
        ]
    },
    {
        "id": "16aa744e037af364",
        "type": "debug",
        "z": "28a8416547d8a5d5",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 850,
        "y": 540,
        "wires": []
    },
    {
        "id": "1714900eea381bcf",
        "type": "inject",
        "z": "28a8416547d8a5d5",
        "name": "open valve",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payloadType": "date",
        "x": 260,
        "y": 640,
        "wires": [
            [
                "b137886b772ea0d2"
            ]
        ]
    },
    {
        "id": "b137886b772ea0d2",
        "type": "function",
        "z": "28a8416547d8a5d5",
        "name": "open",
        "func": "msg.payload = {  \n    command : {\n        // temp_user_unlock_on: false,\n        // reason_for_change: 1,\n        // pressure_measurement_running: false,\n        buzzer_on: true,\n        // buzzer_sound_profile: 1,\n        valve_open: true,\n        // measure_now: true,\n    }\n};\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 390,
        "y": 640,
        "wires": [
            [
                "ed7589d527fde314"
            ]
        ]
    },
    {
        "id": "2ee7f46b1e23c3be",
        "type": "inject",
        "z": "28a8416547d8a5d5",
        "name": "close valve",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payloadType": "date",
        "x": 260,
        "y": 680,
        "wires": [
            [
                "01cffcf2a41fdbf6"
            ]
        ]
    },
    {
        "id": "01cffcf2a41fdbf6",
        "type": "function",
        "z": "28a8416547d8a5d5",
        "name": "close",
        "func": "msg.payload = {  \n    command : {\n        // temp_user_unlock_on: false,\n        // reason_for_change: 1,\n        // pressure_measurement_running: false,\n        buzzer_on: false,\n        // buzzer_sound_profile: 2,\n        valve_open: false,\n        // measure_now: false,\n    }\n};\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 390,
        "y": 680,
        "wires": [
            [
                "ed7589d527fde314"
            ]
        ]
    },
    {
        "id": "c478c1d3715264d5",
        "type": "function",
        "z": "28a8416547d8a5d5",
        "name": "data",
        "func": "let end = new Date();\nlet start = new Date();\nstart.setDate(end.getDate() - 1); // last 7 days.\n\nmsg.payload = {\n    data : {\n        from : start,\n        to : end\n    }\n}\n\nmsg.debug = true;\n\nreturn msg;",
        "outputs": 1,
        "timeout": "",
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 390,
        "y": 720,
        "wires": [
            [
                "ed7589d527fde314"
            ]
        ]
    },
    {
        "id": "8c577a27b2846c21",
        "type": "inject",
        "z": "28a8416547d8a5d5",
        "name": "get data",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 240,
        "y": 720,
        "wires": [
            [
                "c478c1d3715264d5"
            ]
        ]
    },
    {
        "id": "66b4df9cdc60b976",
        "type": "inject",
        "z": "28a8416547d8a5d5",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 320,
        "y": 200,
        "wires": [
            [
                "6592afcafa8f6f46"
            ]
        ]
    },
    {
        "id": "30a5462281a04175",
        "type": "debug",
        "z": "28a8416547d8a5d5",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 830,
        "y": 200,
        "wires": []
    },
    {
        "id": "6592afcafa8f6f46",
        "type": "grohe sense",
        "z": "28a8416547d8a5d5",
        "location": "bdfd803b43c4a2ac",
        "room": "WC",
        "appliance": "Sense1",
        "devicetype": "101",
        "description": "",
        "x": 640,
        "y": 200,
        "wires": [
            [
                "30a5462281a04175"
            ]
        ]
    },
    {
        "id": "ed7589d527fde314",
        "type": "grohe sense",
        "z": "28a8416547d8a5d5",
        "location": "bdfd803b43c4a2ac",
        "room": "Wasserkeller",
        "appliance": "SenseGuard",
        "devicetype": "103",
        "description": "",
        "x": 650,
        "y": 540,
        "wires": [
            [
                "16aa744e037af364"
            ]
        ]
    },
    {
        "id": "bdfd803b43c4a2ac",
        "type": "grohe location",
        "location": "Grohe"
    }
]`

However, imo the problem is the configuration node itself. The initializing status is there immediately once the flow is deployed.

**Comment by windkh** [comment]
Can you try to login here
https://idp2-apigw.cloud.grohe.com/v3/iot/oidc/login

**Comment by windkh** [comment]
Initializing is the default. It will turn green "connected" as soon as the connection to the cloud was established.
Make sure that your node-red instance can connect to the internet

**Comment by windkh** [comment]
And of course the names of the rooms must match to what you configured in your grohe sense app

**Comment by windkh** [comment]
I am quite sure that your Grohe Sense is not in the room "Wasserkeller". And maybe you did not give it the name "SenseGuard".
So cross-check what you configured in your app, choose the correct names and then it should work.

**Comment by rirac** [comment]
That's the important information. I did not notice that.
**Location in configuration node has to be also set correctly according to app.**

Thanks for your very fast response. Going to buy you a coffee :-)

**Comment by windkh** [comment]
I will go to bed now... maybe I will print all the names of houses, rooms, appliances to the console in future....

**Comment by rirac** [comment]
It will be perfect for debug purposes.
