### ISSUE TITLE
Feature Request: Reset daily water consumption at midnight

### ISSUE THREAD

**Issue by PottiMc** [windkh/node-red-contrib-grohe-sense#17]
This is a feature request, not an issue.

The node-red implementation works flawlessly. But if one is tracking the daily water consumption it only resets when new water is used on the next day. For example see the screenshot below. The water consumption is at 200L for example until 06:30 next day when I wake up. Can this be reset to 0 by nodes so it only gets new values after 12pm when they are lower than on the day before?

Especially when in vacation this is very exhilarating for me when I see that water is being used even I am not at home.

![image](https://github.com/windkh/node-red-contrib-grohe-sense/assets/39881308/5e426e4d-8052-4f13-a974-a45bb895e61c)

**Comment by windkh** [comment]
Hm dann müsste ich ja die Werte manipulieren….
welche Daten wurden hier abgefragt? Flowbeispiel wäre hier hilfreich.

**Comment by windkh** [comment]
@PottiMc I just did some tests. I noticed that the data returned by the api changed obviously:
- "timestamp" is now "date"
- maxFlowrate was removed
- the order of values was inverted: now the first one is the newest
So what version do you use? 
How do you create your graphs?
Can you provide some test data?

**Comment by windkh** [comment]
![image](https://github.com/windkh/node-red-contrib-grohe-sense/assets/10910767/12b69c90-b14d-4892-8710-143b87daa24c)
My measurements look like that one

**Comment by PottiMc** [comment]
Anbei mein Flow. Ich nutze Version 0.19.0 und gebe die Daten an HomeAssistant weiter.

Ich frage folgenden Parameter ab: msg.payload.data.withdrawals[0].waterconsumption

Für mich sieht es so aus, als würdest du einen anderen Parameter abfragen. 


[flows.json](https://github.com/user-attachments/files/15573789/flows.json)

**Comment by windkh** [comment]
@PottiMc ok ich schaus mir Abends mal an

**Comment by windkh** [comment]
@PottiMc 
Die Daten im Graph sind die withdrawals. Diese werden nicht aufsummiert sondern absolut pro Stunde geliefert
![image](https://github.com/windkh/node-red-contrib-grohe-sense/assets/10910767/84a3da64-4b1e-494e-85c8-a8237c4296bf)
Letzter Datenpunkt sind 7 Liter um 20:00 Uhr

![image](https://github.com/windkh/node-red-contrib-grohe-sense/assets/10910767/a66e0aaf-de41-48a2-990e-70c3e2708fa9)

Folglich ist es so dass anscheinend Homeassistant im Graph die Daten aufsummiert.  Gibt eine möglichkeit in HA den Graph anders darstellen zu lassen?

**Comment by PottiMc** [comment]
Sieht für mich wirklich so aus als ob die ich an meiner Integration in HomeAssistant arbeiten muss und nicht nach einem Fehler oder ähnlichem in deinem Ablauf. 
Ich poste ein Update sobald ich verlässliche Werte bekomme. Danke dir für die Unterstützung!

**Comment by windkh** [comment]
@PottiMc ok alles klar.
Was sehr schade ist: Grohe hat die API geändert so dass man viel weniger details bekommt als vorher.
Flowrate kann man fast vergessen so ungenau ist das.
Den Verbrauch kann man auch nur pro Stunde sehen und nicht pro minute.

Viel Erfolg.
