### ISSUE TITLE
refreshAccessToken must not crash when connection is down

### ISSUE THREAD

**Issue by windkh** [windkh/node-red-contrib-grohe-sense#18]
[error] Error: getaddrinfo ENOTFOUND idp2-apigw.cloud.grohe.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:128:17)

**Comment by dylan09** [comment]
Also got this two times in the last few weeks. Last yesterday because my DNS was down. 
Only way to get the node back up running is to edit and enter the password again in the location node.
