### ISSUE TITLE
Could not find version 0.20.0 in Home Assistant Node-Red add-on

### ISSUE THREAD

**Issue by dylan09** [windkh/node-red-contrib-grohe-sense#19]
I tried to update with palette manager to the newest version in my Home Assistant Node-Red add-on. But there only version 0.19.0 is available.

How could I get the newest version installed?

Thanks
Ulrich

**Comment by windkh** [comment]
I triggered the update in node red. Should be available now

**Comment by dylan09** [comment]
Perfect. See the update in palette manager. Out of home until Sunday. Will try to install when I am back on Sunday.
