### ISSUE TITLE
No measurement data from API

### ISSUE THREAD

**Issue by mattjgalloway** [windkh/node-red-contrib-grohe-sense#22]
This is not an issue with node-red-contrib-grohe-sense, but I'm opening this here to see if other users are struggling with the same thing at the moment.

I use node-red-contrib-grohe-sense for fetching data from my Grohe Sense Guard. All worked well until about a week or two ago. I started seeing sporadically there was no `measurement` data returned when I fetch history data. I'm using this to fetch the latest measurement of pressure, flow rate and temperature. But now I just get an empty array for `data.measurement` instead of the readings.

My Grohe app still shows the data, so it must be there in the API somewhere!

Is anyone else experiencing this problem?

**Comment by windkh** [comment]
@mattjgalloway Hi Matt, thanks for reporting your findings... I just tried to fetch the data and could see all data. You wrote that this happens "sporadically". How often does that happen and when? Do you fetch the data very often?
I do not have any clue what is going on, but the API was changed in the past, so I would not wonder if something changed again.
Let's observe that!

**Comment by mattjgalloway** [comment]
@windkh Thanks for replying. And silly me. I'm so sorry... actually I was not getting measurements in the Grohe app at all. I thought I was but it was all old data. At some point my Sense Guard stopped sending readings. I turned it off and back on, and it started working again :).

False alarm sorry!
