### ISSUE TITLE
Connection not possible, hangs at Initializing

### ISSUE THREAD

**Issue by DeepflashX** [windkh/node-red-contrib-grohe-sense#23]
Hello there,

I have the latest version running and set up my Grohe Guard. First I had a wrong password which I fixed but now the only thing I see is "initalizing". No debug messages or errors which might indicate, what is the problem.
In general I also have FHEM with grohe ondus adapter running ok (but outdated, therefore many data show improper values).

**Comment by windkh** [comment]
hm then lets check out what is going on

**Comment by DeepflashX** [comment]
what should I do? :)

**Comment by windkh** [comment]
I can help you at the weekend as I am busy with work during the week. Lets set up a teams meeting and then we will see

**Comment by DeepflashX** [comment]
sounds great

**Comment by DeepflashX** [comment]
do you have a mail adress for direct contact?

**Comment by windkh** [comment]
It is in my profile

**Comment by windkh** [comment]
Solution:
The name of the location, room and appliance must exactly match with the ones in the app.

I will improve the output if the location could not be found.

Thanx for reporting.
