### ISSUE TITLE
missing authorization after a period of time

### ISSUE THREAD

**Issue by tommx0** [windkh/node-red-contrib-grohe-sense#5]
Hi,
the  Grohe config node seems to logoff from the server after 1-2 days. I need to reenter the Password in the config node  an redeploy. The error message is: not authorized. Then it reconnects directly.  
Cheers Thomas

**Comment by tommx0** [comment]
here a screenshot:
It seems that the node lost the password. When I enter the passoword it is shown in cleartext. If I open the config node after a error it ist shown as ____PWRD___. Maybe this is a hint .
Thanks a lot
Thomas

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/103289949/173686839-ba925371-05f2-48a7-9ca7-cab41895dbcd.png">

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/103289949/173687035-ae7cb1cc-8a89-42b4-b12e-3c14ff2a8b80.png">

**Comment by windkh** [comment]
I guess that refreshing the token does not work. Do you have a log with the exact error?

**Comment by windkh** [comment]
The output of node red in the console and/or the debug output in the sidebar. Add a debug node which logs node.error

**Comment by tommx0** [comment]
I already placed a debug node. The only output in a case of a failture is "Caught exception: Unauthorized"

**Comment by windkh** [comment]
Hm ok I will check this. Thanks for reporting

**Comment by tommx0** [comment]
Thank you very much. Please tell me if I can support you with further informations

**Comment by tommx0** [comment]
Short Update,
If the Erooro occurs, I only have to enter the Configuration node, change nothing, click on refresh and then deploy "changed nodes". So I aggree that it seems to be the token refresh.  Maybe a "watchdog" for the connection would be helpfull, maybe a auto-Reconnect after connection lost.
Cheers Thomas

**Comment by windkh** [comment]
@tommx0 the access token expires in 3600s and the refresh token in 180days. So I am a bit confused.

So you mentioned after 1-2 days.... is it always after the same time?

**Comment by tommx0** [comment]
It's working right now since 1 day , I would say it never done this before.
I will report state tomorrow.
Thank you very much

**Comment by windkh** [comment]
Sehr gut

**Comment by tommx0** [comment]
Hi,Just to let you know: it's still working. Bugfix helped perfectly, thank you ***@***.*** Wind ***@***.***> schrieb am 20. Juli 2022 um 20:13:Sehr gut—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by windkh** [comment]
Danke fürs testen
