### ISSUE TITLE
Cannot connect to grohe API (special characters in password)

### ISSUE THREAD

**Issue by safakaltun** [windkh/node-red-contrib-grohe-sense#9]
Hi, 

I have been trying to connect to the grohe API using the Node Red add-on on Home Assistant. However, I cannot get the package work. For some reason I get the following warning when I deploy.

[warn] [grohe location:9791d3313d732f27] Login for user myemail@domain.com into grohe cloud failed:/nnull

Node Red can connect to Home Assistant without an issue. I am not sure what the problem is. Could you please help me with it?

**Comment by windkh** [comment]
hm can you try to login with your credentials manually here?
https://idp2-apigw.cloud.grohe.com/v3/iot/oidc/login

**Comment by safakaltun** [comment]
I can login there. I am also able to use the custom hass integration which works for some time until the token times out. :/

**Comment by windkh** [comment]
No idea why it should not work.... I just tested it here. 
Do you run node-red in a separate instance or is it some nod-red from within homeassistant?

**Comment by windkh** [comment]
does your password contain some special characters like & or ?

**Comment by safakaltun** [comment]
I am running it within home assistant.

my password contains the following special characters: 

+{}@

Ps. Thanks for the incredibly fast response speed!

**Comment by windkh** [comment]
Well maybe I need to urlencode the password for the login. Could you do me a favor an change the password to something without special characters? If it works then let me know and then I will try to fix it asap.

**Comment by safakaltun** [comment]
Hey! That solved the issue!

**Comment by windkh** [comment]
Ok thanks for reporting, I will change my own password, too and try to provide a fix soon.
I will add further features to the nodes in future, ... if you have good ideas, your welcome.

**Comment by windkh** [comment]
can you please test Version 0.12.0?

**Comment by aperezva** [comment]
Hi, 

Are you working to have data for the dailey consum in the same date?.I can see now that it´s not possible to get actual watercomsuption. do you know, would it be possible?

Thanksm, for your amazing work

**Comment by windkh** [comment]
@aperezva 
I guess that is already in discussion here: https://github.com/windkh/node-red-contrib-grohe-sense/issues/10

If grohe allows it I will do it
